<?php

/**
 * @file Module code.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_entity_view().
 */
function uitdatabank_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  // Add canonical to page.
  if ($entity->getType() == "event_uitdatabank" && node_is_page($entity)) {

    $uri = $entity->get('field_uitdatabank_same_as')->first();
    if ($uri && $uri->getValue()['uri']) {
      $canonical = array(
        '#type' => 'html_tag',
        '#tag' => 'link',
        '#attributes' => array(
          'name' => 'canonical',
          'content' => $uri,
        ),
      );
      $build['#attached']['html_head'][] = [$canonical, 'canonical'];
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for node_form().
 */
function uitdatabank_form_node_event_uitdatabank_edit_form_alter(array &$form, FormStateInterface $form_state) {

  // Block editing of UiTdatabank fields, but skip for user 1 and if user
  // created the event.
  $current_user = (int) \Drupal::currentUser()->id();
  if ($current_user !== 1 && $current_user !== (int) $form['uid']['widget'][0]['target_id']['#default_value']->id()) {
    foreach ($form as $name => $field) {
      $blocked_fields = [
        'created',
        'langcode',
        'publish_on',
        'status',
        'title',
        'uid',
        'unpublish_on',
      ];

      if (preg_match('/^field_uitdatabank/', $name)) {
        $form[$name]['#disabled'] = TRUE;
      }
      elseif (in_array($name, $blocked_fields)) {
        $form[$name]['#disabled'] = TRUE;
      }
    }
  }
}
