<?php

/**
 * @file
 * Module code.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;

define('UITDATABANK_DEFAULT_IMAGE', 'uitdatabank_default_image.jpg');
define('UITDATABANK_IMAGE_DIRECTORY', 'uitdatabank');

/**
 * Implements hook_entity_view().
 */
function uitdatabank_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {

  // Update canonical on page to UiTdatabank url of the Event.
  if ($entity->getType() == "event_uitdatabank" && node_is_page($entity)) {

    $uri = $entity->get('field_uitdatabank_same_as')->first();
    if ($uri && $uri->getValue()['uri']) {

      foreach ($build['#attached']['html_head_link'] as $index => $item) {
        if ($item[0]['rel'] == 'canonical') {
          $build['#attached']['html_head_link'][$index][0]['href'] = $uri->getValue()['uri'];
          break;
        }
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for node_form().
 */
function uitdatabank_form_node_event_uitdatabank_edit_form_alter(array &$form, FormStateInterface $form_state) {

  // Block editing of UiTdatabank fields, but skip for user 1 and if user
  // created the event.
  $current_user = (int) \Drupal::currentUser()->id();
  if ($current_user !== 1 && $current_user !== (int) $form['uid']['widget'][0]['target_id']['#default_value']->id()) {
    foreach ($form as $name => $field) {
      $blocked_fields = [
        'created',
        'langcode',
        'publish_on',
        'status',
        'title',
        'uid',
        'unpublish_on',
      ];

      if (preg_match('/^field_uitdatabank/', $name)) {
        $form[$name]['#disabled'] = TRUE;
      }
      elseif (in_array($name, $blocked_fields)) {
        $form[$name]['#disabled'] = TRUE;
      }
    }
  }
}
